version: "2"

services:

  plexrequests:
    image: linuxserver/plexrequests
    container_name: plexrequests
    volumes:
    - "${CONFIG_DIR}/plexrequests:/config"
    - /etc/localtime:/etc/localtime:ro
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    restart: always
