version: "2"

services:

  sonarr:
    image: jingke/sonarr_sickbeard_mp4_automator
    container_name: sonarr
    volumes:
    - "${CONFIG_DIR}/sonarr:/config"
    - "${CONFIG_DIR}/scripts:/scripts"
    - "${DATA_DIR}/tv:/tv"
    - "${DATA_DIR}/anime:/anime"
    - "${DOWNLOAD_DIR}:/downloads"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    restart: always
