version: "2"

services:

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: always
