version: "2"

services:

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
    - "${CONFIG_DIR}/jackett:/config"
    - "${DOWNLOAD_DIR}:/downloads"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    restart: always
