version: "2"

services:

  unifi:
    image: linuxserver/unifi
    container_name: unifi
    ports:
    - "3478:3478/udp"
    - "10001:10001/udp"
    - "8080:8080"
    - "8081:8081"
    - "8443:8443"
    - "8843:8843"
    - "8880:8880"
    volumes:
    - "${CONFIG_DIR}/unifi:/config"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "VIRTUAL_PORT=8443"
    - "VIRTUAL_HOST=unifi.${HOSTNAME}"
    restart: always
