version: "2"

services:

  unifi:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi
    ports:
    - 3478:3478/udp
    - 10001:10001/udp
    - 8080:8080
    - 8443:8443
    - 1900:1900/udp #optional
    - 8843:8843 #optional
    - 8880:8880 #optional
    - 6789:6789 #optional
    - 5514:5514/udp #optional
    volumes:
    - "${CONFIG_DIR}/unifi:/config"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "VIRTUAL_PORT=8443"
    - "VIRTUAL_HOST=unifi.${HOSTNAME}"
    restart: always
