version: "2"

services:

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    volumes:
    - "${CONFIG_DIR}/ddclient:/config"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    restart: always
