version: "2"

services:

  plexpy:
    image: linuxserver/tautulli  
    container_name: plexpy
    volumes:
    - "${CONFIG_DIR}/plexpy:/config"
    environment:
    - "PUID=${PUID}"
    - "PGID=${PGID}"
    - "TZ=${TZ}"
    restart: always
